// Drafts the communications team's daily clip email from the items the
// pipeline just built. buildDigest is pure: items in, strings out, with no
// file, network, or clock access, so the same function can later feed an
// email send. The email HTML is deliberately old-fashioned (tables, inline
// styles, no scripts, no external CSS or fonts) because Gmail and Outlook
// strip or ignore anything else.
import { canonicalizeMatchedTerms } from "./matching.js";
import {
  isAssociationItem,
  itemOutletName,
  itemSection,
  itemSourceType,
  SECTION_BRAND,
  SECTION_NATIONAL,
  SECTION_VERMONT,
} from "./relevance.js";
import { groupVisibleStories } from "./outputs.js";
import { cleanText, parseDate } from "./utils.js";

// Older Outlook builds print &apos; literally, so apostrophes use the numeric
// reference that every HTML engine understands.
function escapeXml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

// The fourth heading of the team's email. It held Blue Cross Blue Shield
// Association items, which the reader does not have a section for.
export const SECTION_MORE = "More News";
export const DIGEST_SECTIONS = [SECTION_BRAND, SECTION_VERMONT, SECTION_NATIONAL, SECTION_MORE];

const DEFAULT_TIME_ZONE = "America/New_York";
const SITE_URL = "https://cerulean.news/";
const FOOTER_TEXT =
  "This digest is generated by Cerulean News, which is not affiliated with Blue Cross and Blue Shield of Vermont. Summaries are AI-generated.";
// Gmail clips a message at about 102 KB and hides everything after the cut,
// including the footer, so the digest stays comfortably under 100 KB.
const MAX_HTML_BYTES = 100 * 1000;

const FONT = "Helvetica, Arial, sans-serif";
const COLOR = {
  ink: "#111111",
  muted: "#555555",
  link: "#0033a0",
  rule: "#dddddd",
  band: "#0033a0",
  page: "#f5f8fc",
  card: "#ffffff",
};

function itemLink(item) {
  return item.link || item.url || "";
}

// The digest's own section for an item: association pages go to the fourth
// heading, otherwise the reader's section (already on published items,
// computed for pipeline items that have not been through the JSON Feed yet).
function digestSection(item) {
  if (isAssociationItem(item)) {
    return SECTION_MORE;
  }
  if (item.section === SECTION_BRAND || item.section === SECTION_VERMONT || item.section === SECTION_NATIONAL) {
    return item.section;
  }
  return itemSection({ ...item, matchedTerms: canonicalizeMatchedTerms(item.matchedTerms || []) });
}

function itemTimes(item) {
  return [parseDate(item.pubDate || item.date_published), parseDate(item.firstSeenAt)]
    .filter(Boolean)
    .map((date) => date.valueOf());
}

// An item belongs to the digest when it was published or first seen inside
// the window. A future timestamp never counts, so a mis-dated feed entry
// cannot jump the queue.
function inWindow(item, start, end) {
  return itemTimes(item).some((time) => time > start && time <= end);
}

function sortTime(item) {
  const published = parseDate(item.pubDate || item.date_published)?.valueOf();
  return Number.isFinite(published) ? published : Math.max(0, ...itemTimes(item));
}

// A Google News title ends " - Outlet". Once the outlet has its own line the
// suffix only repeats it.
function stripOutletSuffix(title, outlet) {
  const flat = (text) => text.toLowerCase().replace(/[^a-z0-9]+/g, "");
  const match = /^(.*\S)\s+-\s+([^-]{2,80})$/.exec(title);
  if (match && flat(match[2]) && flat(outlet).includes(flat(match[2]))) {
    return match[1];
  }
  return title;
}

function safeHref(url) {
  return /^https?:\/\//i.test(url || "") ? url : "";
}

function sentimentText(entry) {
  const label = entry.sentiment || "";
  const score = Number.isFinite(entry.sentimentScore) ? String(Math.round(entry.sentimentScore)) : "";
  if (label && score) {
    return `Sentiment: ${score} · ${label}`;
  }
  return label || score ? `Sentiment: ${label || score}` : "";
}

// `ordered` is newest first: the newest report leads and the rest become the
// "Also covered by" line.
function buildEntry(ordered, section) {
  const lead = ordered[0];
  const outlet = itemOutletName(lead) || lead.sourceName || "";
  const brand = section === SECTION_BRAND && lead.sentimentEligible !== false;
  const entry = {
    title: stripOutletSuffix(cleanText(lead.title || ""), outlet) || cleanText(lead.title || "") || "Untitled",
    url: safeHref(itemLink(lead)),
    outlet,
    summary: cleanText(lead.summary || ""),
    publishedAt: parseDate(lead.pubDate || lead.date_published)?.toISOString() || null,
    alsoCoveredBy: ordered.slice(1).map((member) => ({
      outlet: itemOutletName(member) || member.sourceName || "",
      url: safeHref(itemLink(member)),
    })),
  };
  if (brand && lead.sentiment) {
    entry.sentiment = lead.sentiment;
  }
  if (brand && Number.isFinite(lead.sentimentScore)) {
    entry.sentimentScore = lead.sentimentScore;
  }
  return entry;
}

// Collects the in-window items into ordered sections of collapsed entries.
function collectSections(items, start, end) {
  const visible = items.filter((item) => item.relevant !== false);
  // Grouping runs over every visible item, not just the window: the term
  // weights need the whole feed to match how the reader groups, and a story
  // covered again today should still join yesterday's report of it. Items
  // that already carry a storyGroupId (a published feed) keep their group.
  const groups = visible.some((item) => item.storyGroupId) ? null : groupVisibleStories(visible);
  const groupOf = (item) => (groups ? groups.get(item) : null) || (item.storyGroupId ? item.storyGroupId : null);
  const clusters = new Map();
  for (const item of visible) {
    if (itemSourceType(item) !== "News" || !inWindow(item, start, end)) {
      continue;
    }
    // Association pages are the fourth heading by definition, so they never
    // fold into a news story that happens to cover the same event.
    const grouped = isAssociationItem(item) ? null : groupOf(item);
    const key = grouped ? (typeof grouped === "string" ? grouped : grouped.id) : Symbol("single");
    if (!clusters.has(key)) {
      clusters.set(key, []);
    }
    clusters.get(key).push(item);
  }

  // The newest report leads an entry and decides its section.
  const entries = [...clusters.values()].map((members) => {
    const ordered = [...members].sort((a, b) => sortTime(b) - sortTime(a));
    const section = digestSection(ordered[0]);
    return { section, time: sortTime(ordered[0]), entry: buildEntry(ordered, section) };
  });
  return DIGEST_SECTIONS.map((name) => ({
    name,
    entries: entries
      .filter((candidate) => candidate.section === name)
      .sort((a, b) => b.time - a.time)
      .map(({ entry }) => entry),
  })).filter((section) => section.entries.length > 0);
}

function formatDigestDate(now, timeZone) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  }).formatToParts(now);
  const part = (type) => parts.find((entry) => entry.type === type)?.value || "";
  return `${part("weekday")}, ${part("month")} ${part("day")}, ${part("year")}`;
}

function countStories(sections) {
  return sections.reduce((total, section) => total + section.entries.length, 0);
}

function storyLabel(count) {
  return `${count} ${count === 1 ? "story" : "stories"}`;
}

// ---------------------------------------------------------------------------
// Plain text
// ---------------------------------------------------------------------------

function renderText(sections, { dateLabel, windowHours, omitted }) {
  const lines = ["CERULEAN NEWS CLIPS", `${dateLabel} - ${storyLabel(countStories(sections))}`, ""];
  if (sections.length === 0) {
    lines.push(`No new stories in the last ${windowHours} hours.`, "");
  }
  for (const section of sections) {
    lines.push(section.name.toUpperCase(), "-".repeat(section.name.length));
    for (const entry of section.entries) {
      lines.push(`* ${entry.title}`);
      const meta = [entry.outlet, sentimentText(entry)].filter(Boolean).join(" | ");
      if (meta) {
        lines.push(`  ${meta}`);
      }
      if (entry.summary) {
        lines.push(`  ${entry.summary}`);
      }
      if (entry.alsoCoveredBy.length > 0) {
        lines.push(`  Also covered by: ${entry.alsoCoveredBy.map((other) => other.outlet).join(", ")}`);
      }
      if (entry.url) {
        lines.push(`  ${entry.url}`);
      }
      lines.push("");
    }
  }
  if (omitted > 0) {
    lines.push(`${omitted} more ${omitted === 1 ? "story is" : "stories are"} not shown. See ${SITE_URL}`, "");
  }
  lines.push("--", FOOTER_TEXT);
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Email HTML
// ---------------------------------------------------------------------------

const cell = (style, content, attrs = "") => `<td${attrs} style="font-family:${FONT};${style}">${content}</td>`;

function link(url, label, style) {
  const text = escapeXml(label);
  return url ? `<a href="${escapeXml(url)}" style="${style}">${text}</a>` : text;
}

function entryHtml(entry) {
  const meta = [escapeXml(entry.outlet), escapeXml(sentimentText(entry))].filter(Boolean).join(" &middot; ");
  const parts = [
    `<p style="margin:0 0 4px 0;font-size:17px;line-height:22px;font-weight:bold;">${link(entry.url, entry.title, `color:${COLOR.link};text-decoration:none;`)}</p>`,
  ];
  if (meta) {
    parts.push(`<p style="margin:0 0 4px 0;font-size:13px;line-height:18px;color:${COLOR.muted};">${meta}</p>`);
  }
  if (entry.summary) {
    parts.push(`<p style="margin:0 0 4px 0;font-size:15px;line-height:21px;color:${COLOR.ink};">${escapeXml(entry.summary)}</p>`);
  }
  if (entry.alsoCoveredBy.length > 0) {
    const others = entry.alsoCoveredBy
      .map((other) => link(other.url, other.outlet, `color:${COLOR.muted};text-decoration:underline;`))
      .join(", ");
    parts.push(`<p style="margin:0;font-size:13px;line-height:18px;color:${COLOR.muted};"><strong>Also covered by:</strong> ${others}</p>`);
  }
  return `<tr>${cell(`padding:12px 20px;border-bottom:1px solid ${COLOR.rule};`, parts.join(""))}</tr>`;
}

function sectionHtml(section) {
  return [
    `<tr>${cell(`padding:8px 20px;background-color:${COLOR.band};font-size:13px;line-height:18px;font-weight:bold;letter-spacing:1px;text-transform:uppercase;color:#ffffff;`, escapeXml(section.name), ` bgcolor="${COLOR.band}"`)}</tr>`,
    ...section.entries.map(entryHtml),
  ].join("");
}

function renderHtml(sections, { subject, dateLabel, windowHours, omitted }) {
  const body = sections.length > 0
    ? sections.map(sectionHtml).join("")
    : `<tr>${cell(`padding:20px;font-size:15px;line-height:21px;color:${COLOR.ink};`, `No new stories in the last ${windowHours} hours.`)}</tr>`;
  const omittedRow = omitted > 0
    ? `<tr>${cell(`padding:12px 20px;font-size:13px;line-height:18px;color:${COLOR.muted};`, `${omitted} more ${omitted === 1 ? "story is" : "stories are"} not shown. <a href="${SITE_URL}" style="color:${COLOR.link};">See them on Cerulean News</a>.`)}</tr>`
    : "";
  // The outer table fills the client's window and carries the page colour;
  // the inner one is 600 wide for Outlook (which honors the attribute) and
  // shrinks on phones (max-width, which Outlook ignores).
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<title>${escapeXml(subject)}</title>
</head>
<body style="margin:0;padding:0;background-color:${COLOR.page};">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${COLOR.page}" style="background-color:${COLOR.page};">
<tr><td align="center" style="padding:16px 8px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" bgcolor="${COLOR.card}" style="width:100%;max-width:600px;background-color:${COLOR.card};border:1px solid ${COLOR.rule};">
<tr>${cell(`padding:20px 20px 12px 20px;border-bottom:4px solid ${COLOR.band};`, `<p style="margin:0;font-size:24px;line-height:28px;font-weight:bold;color:${COLOR.ink};">Cerulean News clips</p><p style="margin:4px 0 0 0;font-size:14px;line-height:20px;color:${COLOR.muted};">${escapeXml(dateLabel)} &middot; ${escapeXml(storyLabel(countStories(sections)))}</p>`)}</tr>
${body}
${omittedRow}
<tr>${cell(`padding:16px 20px;font-size:12px;line-height:17px;color:${COLOR.muted};`, escapeXml(FOOTER_TEXT))}</tr>
</table>
</td></tr>
</table>
</body>
</html>
`;
}

const encoder = new TextEncoder();

// Builds the digest for the last `windowHours` before `now`. `sections` lists
// only the headings that have stories, in the team's order. If a very busy
// day would push the HTML past the size limit, the oldest stories from the
// last sections are left out and the email says how many.
export function buildDigest(items, { now = new Date(), windowHours = 24, timeZone = DEFAULT_TIME_ZONE } = {}) {
  const end = now.valueOf();
  const start = end - windowHours * 60 * 60 * 1000;
  const sections = collectSections(items || [], start, end);
  const dateLabel = formatDigestDate(now, timeZone);

  let omitted = 0;
  for (;;) {
    const subject = `Cerulean News clips - ${dateLabel} (${storyLabel(countStories(sections))})`;
    const html = renderHtml(sections, { subject, dateLabel, windowHours, omitted });
    if (encoder.encode(html).length <= MAX_HTML_BYTES || countStories(sections) === 0) {
      return {
        subject,
        html,
        text: renderText(sections, { dateLabel, windowHours, omitted }),
        sections,
        itemCount: countStories(sections),
      };
    }
    const last = sections[sections.length - 1];
    last.entries.pop();
    if (last.entries.length === 0) {
      sections.pop();
    }
    omitted += 1;
  }
}

// ---------------------------------------------------------------------------
// The standalone page
// ---------------------------------------------------------------------------

// A copy-ready page around the email: the email renders in a frame exactly as
// a mail client would show it, and the button puts the HTML (with a plain
// text alternative) on the clipboard for pasting into a new message.
// "Sep 28, 2026, 7:04 PM" in Eastern time, the reader's dateline format.
function formatGeneratedAt(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return String(value || "");
  }
  return new Intl.DateTimeFormat("en-US", {
    timeZone: DEFAULT_TIME_ZONE,
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

export function buildDigestPage(digest, { generatedAt }) {
  const frameHtml = escapeXml(digest.html);
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Clip email draft | Cerulean News</title>
    <meta name="robots" content="noindex">
    <link rel="icon" href="favicon.ico" sizes="any">
    <meta name="theme-color" content="#0033a0">
    <style>
      :root {
        --fg: #111;
        --muted: #555;
        --link: #0000cc;
        --rule: #ccc;
        --surface: #f5f8fc;
        --bg: #fff;
        --bar-1: #0033a0;
        --bar-2: #111;
        --bar-3: #418fde;
      }
      body {
        margin: 0;
        background: var(--bg);
        color: var(--fg);
        font-family: Helvetica, Arial, sans-serif;
        font-size: 16px;
        line-height: 1.45;
      }
      .page { max-width: 560px; margin: 0 auto; padding: 18px 16px 48px; }
      .topbar { display: flex; flex-wrap: wrap; gap: 12px; font-size: 0.9rem; margin-bottom: 24px; }
      .topbar a, .topbar button {
        display: inline-block;
        padding: 4px 12px;
        border: 1px solid var(--fg);
        background: transparent;
        color: var(--fg);
        font: inherit;
        font-size: 0.9rem;
        text-decoration: none;
        cursor: pointer;
      }
      .topbar a:hover, .topbar button:hover { background: var(--surface); }
      h1 { margin: 0 0 6px; font-size: 1.65rem; font-weight: 700; }
      .tricolor { display: flex; height: 5px; margin: 0 0 18px; }
      .tricolor span { flex: 1; }
      .c1 { background: var(--bar-1); }
      .c2 { background: var(--bar-2); }
      .c3 { background: var(--bar-3); }
      a { color: var(--link); }
      a:focus-visible, button:focus-visible { outline: 3px solid var(--bar-3); outline-offset: 2px; }
      .note { margin: 0 0 14px; color: var(--muted); font-size: 0.92rem; }
      #status { min-height: 1.4em; margin: 0 0 14px; font-size: 0.92rem; }
      iframe { display: block; width: 100%; height: 480px; border: 1px solid var(--rule); background: #fff; }
      footer { margin-top: 24px; font-size: 0.8rem; color: var(--muted); line-height: 1.45; }
      footer::before {
        content: "";
        display: block;
        height: 5px;
        margin-bottom: 16px;
        background: linear-gradient(to right, var(--bar-1) 0 33.333%, var(--bar-2) 33.333% 66.666%, var(--bar-3) 66.666% 100%);
      }
      .affiliation {
        margin: 0 0 14px;
        padding: 10px 12px;
        border: 2px solid var(--bar-1);
        border-radius: 4px;
        color: var(--fg);
        font-size: 15px;
      }
      .affiliation strong { color: var(--bar-1); }
      textarea { display: none; }
    </style>
    <link rel="stylesheet" href="gate.css">
    <script>
      try { if (localStorage.getItem("blueNewsAuth") === "true") document.documentElement.classList.add("authenticated"); } catch (e) {}
    </script>
  </head>
  <body>
    <script src="gate.js"></script>
    <div class="page">
      <div class="topbar">
        <a href="./">Back to stories</a>
        <button type="button" id="copy-email">Copy email</button>
        <a href="digest.json">JSON Feed</a>
      </div>
      <main>
        <h1>Clip email draft</h1>
        <div class="tricolor" aria-hidden="true"><span class="c1"></span><span class="c2"></span><span class="c3"></span></div>
        <p class="note"><strong>${escapeXml(digest.subject)}</strong></p>
        <p class="note">Generated ${escapeXml(formatGeneratedAt(generatedAt))} from the last 24 hours of stories. Press Copy email, then paste into a new message. Review it before sending.</p>
        <p id="status" role="status" aria-live="polite"></p>
        <iframe id="preview" title="Email preview" sandbox="allow-same-origin" srcdoc="${frameHtml}"></iframe>
        <textarea id="digest-text" readonly>${escapeXml(digest.text)}</textarea>
      </main>
      <footer>
        <p class="affiliation">
          <strong>Not affiliated.</strong> Cerulean News is an independent personal
          project. It is not affiliated with, endorsed by, or operated by Blue
          Cross and Blue Shield of Vermont or the Blue Cross Blue Shield
          Association.
        </p>
      </footer>
    </div>
    <script>
      (function () {
        var frame = document.getElementById("preview");
        var status = document.getElementById("status");
        function fit() {
          try { frame.style.height = frame.contentDocument.documentElement.scrollHeight + "px"; } catch (e) {}
        }
        frame.addEventListener("load", fit);
        function done(message) { status.textContent = message; }
        function fallback() {
          try {
            var selection = frame.contentWindow.getSelection();
            selection.removeAllRanges();
            selection.selectAllChildren(frame.contentDocument.body);
            var ok = frame.contentDocument.execCommand("copy");
            selection.removeAllRanges();
            done(ok ? "Copied. Paste into a new message." : "Copy failed. Select the preview and copy it by hand.");
          } catch (e) {
            done("Copy failed. Select the preview and copy it by hand.");
          }
        }
        document.getElementById("copy-email").addEventListener("click", function () {
          var html = frame.srcdoc;
          var text = document.getElementById("digest-text").value;
          if (navigator.clipboard && window.ClipboardItem) {
            navigator.clipboard.write([new ClipboardItem({
              "text/html": new Blob([html], { type: "text/html" }),
              "text/plain": new Blob([text], { type: "text/plain" })
            })]).then(function () { done("Copied. Paste into a new message."); }, fallback);
          } else {
            fallback();
          }
        });
      })();
    </script>
  </body>
</html>
`;
}
